package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private AnswerId id;
	private Question question;
	private Seed seed;
	private Integer correct;
	private String content;
	private String expln;

	public Answer() {
	}

	public Answer(AnswerId id, Question question, Seed seed) {
		this.id = id;
		this.question = question;
		this.seed = seed;
	}

	public Answer(AnswerId id, Question question, Seed seed, Integer correct,
			String content, String expln) {
		this.id = id;
		this.question = question;
		this.seed = seed;
		this.correct = correct;
		this.content = content;
		this.expln = expln;
	}

	public AnswerId getId() {
		return this.id;
	}

	public void setId(AnswerId id) {
		this.id = id;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Seed getSeed() {
		return this.seed;
	}

	public void setSeed(Seed seed) {
		this.seed = seed;
	}

	public Integer getCorrect() {
		return this.correct;
	}

	public void setCorrect(Integer correct) {
		this.correct = correct;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getExpln() {
		return this.expln;
	}

	public void setExpln(String expln) {
		this.expln = expln;
	}

}
