package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Asques generated by hbm2java
 */
public class Asques implements java.io.Serializable {

	private Integer id;
	private Integer aid;
	private Integer tid;
	private String ansidArray;

	public Asques() {
	}

	public Asques(Integer aid, Integer tid, String ansidArray) {
		this.aid = aid;
		this.tid = tid;
		this.ansidArray = ansidArray;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getAnsidArray() {
		return this.ansidArray;
	}

	public void setAnsidArray(String ansidArray) {
		this.ansidArray = ansidArray;
	}

}
