package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Assessment generated by hbm2java
 */
public class Assessment implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date tstart;
	private Date tend;
	private Integer difficulty;
	private Integer retry;
	private Integer pcorrect;
	private Integer pwrong;

	public Assessment() {
	}

	public Assessment(String title, Date tstart, Date tend, Integer difficulty,
			Integer retry, Integer pcorrect, Integer pwrong) {
		this.title = title;
		this.tstart = tstart;
		this.tend = tend;
		this.difficulty = difficulty;
		this.retry = retry;
		this.pcorrect = pcorrect;
		this.pwrong = pwrong;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTstart() {
		return this.tstart;
	}

	public void setTstart(Date tstart) {
		this.tstart = tstart;
	}

	public Date getTend() {
		return this.tend;
	}

	public void setTend(Date tend) {
		this.tend = tend;
	}

	public Integer getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(Integer difficulty) {
		this.difficulty = difficulty;
	}

	public Integer getRetry() {
		return this.retry;
	}

	public void setRetry(Integer retry) {
		this.retry = retry;
	}

	public Integer getPcorrect() {
		return this.pcorrect;
	}

	public void setPcorrect(Integer pcorrect) {
		this.pcorrect = pcorrect;
	}

	public Integer getPwrong() {
		return this.pwrong;
	}

	public void setPwrong(Integer pwrong) {
		this.pwrong = pwrong;
	}

}
