package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assessment generated by hbm2java
 */
public class Assessment implements java.io.Serializable {

	private Integer aid;
	private Course course;
	private String title;
	private Date tstart;
	private Date tend;
	private String difficulty;
	private Integer retry;
	private Integer corrPts;
	private Integer penalPts;
	private String scoreSelect;
	private Set attempts = new HashSet(0);
	private Set questions = new HashSet(0);

	public Assessment() {
	}

	public Assessment(Course course) {
		this.course = course;
	}

	public Assessment(Course course, String title, Date tstart, Date tend,
			String difficulty, Integer retry, Integer corrPts,
			Integer penalPts, String scoreSelect, Set attempts, Set questions) {
		this.course = course;
		this.title = title;
		this.tstart = tstart;
		this.tend = tend;
		this.difficulty = difficulty;
		this.retry = retry;
		this.corrPts = corrPts;
		this.penalPts = penalPts;
		this.scoreSelect = scoreSelect;
		this.attempts = attempts;
		this.questions = questions;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTstart() {
		return this.tstart;
	}

	public void setTstart(Date tstart) {
		this.tstart = tstart;
	}

	public Date getTend() {
		return this.tend;
	}

	public void setTend(Date tend) {
		this.tend = tend;
	}

	public String getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(String difficulty) {
		this.difficulty = difficulty;
	}

	public Integer getRetry() {
		return this.retry;
	}

	public void setRetry(Integer retry) {
		this.retry = retry;
	}

	public Integer getCorrPts() {
		return this.corrPts;
	}

	public void setCorrPts(Integer corrPts) {
		this.corrPts = corrPts;
	}

	public Integer getPenalPts() {
		return this.penalPts;
	}

	public void setPenalPts(Integer penalPts) {
		this.penalPts = penalPts;
	}

	public String getScoreSelect() {
		return this.scoreSelect;
	}

	public void setScoreSelect(String scoreSelect) {
		this.scoreSelect = scoreSelect;
	}

	public Set getAttempts() {
		return this.attempts;
	}

	public void setAttempts(Set attempts) {
		this.attempts = attempts;
	}

	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

}
