package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Attempt generated by hbm2java
 */
public class Attempt implements java.io.Serializable {

	private Integer id;
	private Integer aid;
	private Integer sid;
	private Integer score;
	private Date time;
	private String stuans;

	public Attempt() {
	}

	public Attempt(Integer aid, Integer sid, Integer score, Date time,
			String stuans) {
		this.aid = aid;
		this.sid = sid;
		this.score = score;
		this.time = time;
		this.stuans = stuans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getStuans() {
		return this.stuans;
	}

	public void setStuans(String stuans) {
		this.stuans = stuans;
	}

}
