package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * AttemptId generated by hbm2java
 */
public class AttemptId implements java.io.Serializable {

	private int atid;
	private String sid;
	private int aid;
	private int qid;

	public AttemptId() {
	}

	public AttemptId(int atid, String sid, int aid, int qid) {
		this.atid = atid;
		this.sid = sid;
		this.aid = aid;
		this.qid = qid;
	}

	public int getAtid() {
		return this.atid;
	}

	public void setAtid(int atid) {
		this.atid = atid;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttemptId))
			return false;
		AttemptId castOther = (AttemptId) other;

		return (this.getAtid() == castOther.getAtid())
				&& ((this.getSid() == castOther.getSid()) || (this.getSid() != null
						&& castOther.getSid() != null && this.getSid().equals(
						castOther.getSid())))
				&& (this.getAid() == castOther.getAid())
				&& (this.getQid() == castOther.getQid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAtid();
		result = 37 * result
				+ (getSid() == null ? 0 : this.getSid().hashCode());
		result = 37 * result + this.getAid();
		result = 37 * result + this.getQid();
		return result;
	}

}
