package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private ChapterId id;
	private Textbook textbook;
	private String title;
	private Set sections = new HashSet(0);

	public Chapter() {
	}

	public Chapter(ChapterId id, Textbook textbook) {
		this.id = id;
		this.textbook = textbook;
	}

	public Chapter(ChapterId id, Textbook textbook, String title, Set sections) {
		this.id = id;
		this.textbook = textbook;
		this.title = title;
		this.sections = sections;
	}

	public ChapterId getId() {
		return this.id;
	}

	public void setId(ChapterId id) {
		this.id = id;
	}

	public Textbook getTextbook() {
		return this.textbook;
	}

	public void setTextbook(Textbook textbook) {
		this.textbook = textbook;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getSections() {
		return this.sections;
	}

	public void setSections(Set sections) {
		this.sections = sections;
	}

}
