package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * ChapterId generated by hbm2java
 */
public class ChapterId implements java.io.Serializable {

	private int chapid;
	private String isbn;

	public ChapterId() {
	}

	public ChapterId(int chapid, String isbn) {
		this.chapid = chapid;
		this.isbn = isbn;
	}

	public int getChapid() {
		return this.chapid;
	}

	public void setChapid(int chapid) {
		this.chapid = chapid;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChapterId))
			return false;
		ChapterId castOther = (ChapterId) other;

		return (this.getChapid() == castOther.getChapid())
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null
						&& castOther.getIsbn() != null && this.getIsbn()
						.equals(castOther.getIsbn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChapid();
		result = 37 * result
				+ (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		return result;
	}

}
