package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private Integer id;
	private Integer bid;
	private String title;

	public Chapter() {
	}

	public Chapter(Integer bid, String title) {
		this.bid = bid;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
