package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private String cid;
	private Faculty faculty;
	private String token;
	private String name;
	private Date tstart;
	private Date tend;
	private String level;
	private Integer volume;
	private Integer maxenroll;
	private Set textbooks = new HashSet(0);
	private Set students = new HashSet(0);
	private Set students_1 = new HashSet(0);
	private Set assessments = new HashSet(0);
	private Set topics = new HashSet(0);

	public Course() {
	}

	public Course(String cid, Faculty faculty) {
		this.cid = cid;
		this.faculty = faculty;
	}

	public Course(String cid, Faculty faculty, String token, String name,
			Date tstart, Date tend, String level, Integer volume,
			Integer maxenroll, Set textbooks, Set students, Set students_1,
			Set assessments, Set topics) {
		this.cid = cid;
		this.faculty = faculty;
		this.token = token;
		this.name = name;
		this.tstart = tstart;
		this.tend = tend;
		this.level = level;
		this.volume = volume;
		this.maxenroll = maxenroll;
		this.textbooks = textbooks;
		this.students = students;
		this.students_1 = students_1;
		this.assessments = assessments;
		this.topics = topics;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getTstart() {
		return this.tstart;
	}

	public void setTstart(Date tstart) {
		this.tstart = tstart;
	}

	public Date getTend() {
		return this.tend;
	}

	public void setTend(Date tend) {
		this.tend = tend;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	public Integer getMaxenroll() {
		return this.maxenroll;
	}

	public void setMaxenroll(Integer maxenroll) {
		this.maxenroll = maxenroll;
	}

	public Set getTextbooks() {
		return this.textbooks;
	}

	public void setTextbooks(Set textbooks) {
		this.textbooks = textbooks;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getStudents_1() {
		return this.students_1;
	}

	public void setStudents_1(Set students_1) {
		this.students_1 = students_1;
	}

	public Set getAssessments() {
		return this.assessments;
	}

	public void setAssessments(Set assessments) {
		this.assessments = assessments;
	}

	public Set getTopics() {
		return this.topics;
	}

	public void setTopics(Set topics) {
		this.topics = topics;
	}

}
