package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private String id;
	private String token;
	private String name;
	private Date tstart;
	private Date tend;
	private String level;
	private Integer volume;
	private Integer enroll;
	private Integer pid;
	private Integer taid;
	private Integer bid;

	public Course() {
	}

	public Course(String id) {
		this.id = id;
	}

	public Course(String id, String token, String name, Date tstart, Date tend,
			String level, Integer volume, Integer enroll, Integer pid,
			Integer taid, Integer bid) {
		this.id = id;
		this.token = token;
		this.name = name;
		this.tstart = tstart;
		this.tend = tend;
		this.level = level;
		this.volume = volume;
		this.enroll = enroll;
		this.pid = pid;
		this.taid = taid;
		this.bid = bid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getTstart() {
		return this.tstart;
	}

	public void setTstart(Date tstart) {
		this.tstart = tstart;
	}

	public Date getTend() {
		return this.tend;
	}

	public void setTend(Date tend) {
		this.tend = tend;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	public Integer getEnroll() {
		return this.enroll;
	}

	public void setEnroll(Integer enroll) {
		this.enroll = enroll;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Integer getTaid() {
		return this.taid;
	}

	public void setTaid(Integer taid) {
		this.taid = taid;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

}
