package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Cover generated by hbm2java
 */
public class Cover implements java.io.Serializable {

	private Integer id;
	private Integer cid;
	private Integer tid;

	public Cover() {
	}

	public Cover(Integer cid, Integer tid) {
		this.cid = cid;
		this.tid = tid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

}
