package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Enroll generated by hbm2java
 */
public class Enroll implements java.io.Serializable {

	private Integer id;
	private Integer cid;
	private Integer sid;

	public Enroll() {
	}

	public Enroll(Integer cid, Integer sid) {
		this.cid = cid;
		this.sid = sid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

}
