package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty implements java.io.Serializable {

	private String fid;
	private String name;
	private Set courses = new HashSet(0);

	public Faculty() {
	}

	public Faculty(String fid) {
		this.fid = fid;
	}

	public Faculty(String fid, String name, Set courses) {
		this.fid = fid;
		this.name = name;
		this.courses = courses;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
