package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Section generated by hbm2java
 */
public class Section implements java.io.Serializable {

	private Integer id;
	private Integer chapid;
	private String title;

	public Section() {
	}

	public Section(Integer chapid, String title) {
		this.chapid = chapid;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getChapid() {
		return this.chapid;
	}

	public void setChapid(Integer chapid) {
		this.chapid = chapid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
