package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class Section implements java.io.Serializable {

	private SectionId id;
	private Chapter chapter;
	private String title;
	private Set subsections = new HashSet(0);

	public Section() {
	}

	public Section(SectionId id, Chapter chapter) {
		this.id = id;
		this.chapter = chapter;
	}

	public Section(SectionId id, Chapter chapter, String title, Set subsections) {
		this.id = id;
		this.chapter = chapter;
		this.title = title;
		this.subsections = subsections;
	}

	public SectionId getId() {
		return this.id;
	}

	public void setId(SectionId id) {
		this.id = id;
	}

	public Chapter getChapter() {
		return this.chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getSubsections() {
		return this.subsections;
	}

	public void setSubsections(Set subsections) {
		this.subsections = subsections;
	}

}
