package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * SeedId generated by hbm2java
 */
public class SeedId implements java.io.Serializable {

	private int qid;
	private int seed;

	public SeedId() {
	}

	public SeedId(int qid, int seed) {
		this.qid = qid;
		this.seed = seed;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public int getSeed() {
		return this.seed;
	}

	public void setSeed(int seed) {
		this.seed = seed;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeedId))
			return false;
		SeedId castOther = (SeedId) other;

		return (this.getQid() == castOther.getQid())
				&& (this.getSeed() == castOther.getSeed());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getQid();
		result = 37 * result + this.getSeed();
		return result;
	}

}
