package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Seed generated by hbm2java
 */
public class Seed implements java.io.Serializable {

	private SeedId id;
	private Question question;
	private String content;
	private String hint;
	private String explanation;
	private Set attempts = new HashSet(0);
	private Set answers = new HashSet(0);

	public Seed() {
	}

	public Seed(SeedId id, Question question) {
		this.id = id;
		this.question = question;
	}

	public Seed(SeedId id, Question question, String content, String hint,
			String explanation, Set attempts, Set answers) {
		this.id = id;
		this.question = question;
		this.content = content;
		this.hint = hint;
		this.explanation = explanation;
		this.attempts = attempts;
		this.answers = answers;
	}

	public SeedId getId() {
		return this.id;
	}

	public void setId(SeedId id) {
		this.id = id;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHint() {
		return this.hint;
	}

	public void setHint(String hint) {
		this.hint = hint;
	}

	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	public Set getAttempts() {
		return this.attempts;
	}

	public void setAttempts(Set attempts) {
		this.attempts = attempts;
	}

	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

}
