package edu.ncsu.gradiance.dao;

// Generated Oct 15, 2014 11:40:44 AM by Hibernate Tools 4.3.1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private String level;
	private String ista;

	public Student() {
	}

	public Student(String name, String level, String ista) {
		this.name = name;
		this.level = level;
		this.ista = ista;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getIsta() {
		return this.ista;
	}

	public void setIsta(String ista) {
		this.ista = ista;
	}

}
