package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private String sid;
	private String name;
	private String level;
	private Ta ta;
	private Set courses = new HashSet(0);
	private Set attempts = new HashSet(0);
	private Set courses_1 = new HashSet(0);

	public Student() {
	}

	public Student(String sid) {
		this.sid = sid;
	}

	public Student(String sid, String name, String level, Ta ta, Set courses,
			Set attempts, Set courses_1) {
		this.sid = sid;
		this.name = name;
		this.level = level;
		this.ta = ta;
		this.courses = courses;
		this.attempts = attempts;
		this.courses_1 = courses_1;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Ta getTa() {
		return this.ta;
	}

	public void setTa(Ta ta) {
		this.ta = ta;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getAttempts() {
		return this.attempts;
	}

	public void setAttempts(Set attempts) {
		this.attempts = attempts;
	}

	public Set getCourses_1() {
		return this.courses_1;
	}

	public void setCourses_1(Set courses_1) {
		this.courses_1 = courses_1;
	}

}
