package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * Subsection generated by hbm2java
 */
public class Subsection implements java.io.Serializable {

	private SubsectionId id;
	private Section section;
	private String title;

	public Subsection() {
	}

	public Subsection(SubsectionId id, Section section) {
		this.id = id;
		this.section = section;
	}

	public Subsection(SubsectionId id, Section section, String title) {
		this.id = id;
		this.section = section;
		this.title = title;
	}

	public SubsectionId getId() {
		return this.id;
	}

	public void setId(SubsectionId id) {
		this.id = id;
	}

	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
