package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

/**
 * SubsectionId generated by hbm2java
 */
public class SubsectionId implements java.io.Serializable {

	private int chapid;
	private int secid;
	private int subsecid;
	private String isbn;

	public SubsectionId() {
	}

	public SubsectionId(int chapid, int secid, int subsecid, String isbn) {
		this.chapid = chapid;
		this.secid = secid;
		this.subsecid = subsecid;
		this.isbn = isbn;
	}

	public int getChapid() {
		return this.chapid;
	}

	public void setChapid(int chapid) {
		this.chapid = chapid;
	}

	public int getSecid() {
		return this.secid;
	}

	public void setSecid(int secid) {
		this.secid = secid;
	}

	public int getSubsecid() {
		return this.subsecid;
	}

	public void setSubsecid(int subsecid) {
		this.subsecid = subsecid;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubsectionId))
			return false;
		SubsectionId castOther = (SubsectionId) other;

		return (this.getChapid() == castOther.getChapid())
				&& (this.getSecid() == castOther.getSecid())
				&& (this.getSubsecid() == castOther.getSubsecid())
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null
						&& castOther.getIsbn() != null && this.getIsbn()
						.equals(castOther.getIsbn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChapid();
		result = 37 * result + this.getSecid();
		result = 37 * result + this.getSubsecid();
		result = 37 * result
				+ (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		return result;
	}

}
