package edu.ncsu.gradiance.dao;

// Generated Oct 20, 2014 5:39:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Textbook generated by hbm2java
 */
public class Textbook implements java.io.Serializable {

	private String isbn;
	private String title;
	private String author;
	private Set courses = new HashSet(0);
	private Set chapters = new HashSet(0);

	public Textbook() {
	}

	public Textbook(String isbn) {
		this.isbn = isbn;
	}

	public Textbook(String isbn, String title, String author, Set courses,
			Set chapters) {
		this.isbn = isbn;
		this.title = title;
		this.author = author;
		this.courses = courses;
		this.chapters = chapters;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getChapters() {
		return this.chapters;
	}

	public void setChapters(Set chapters) {
		this.chapters = chapters;
	}

}
